/* test_string.c generated by valac 0.28.0, the Vala compiler
 * generated from test_string.vala, do not modify */

/* Copyright (C) 2015, WSID   */
/* This file is part of Crank System.
 *
 *  Crank System is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation, either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  Crank System is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with Crank System.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <crankbase.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);



gint _vala_main (gchar** args, int args_length1);
void test_read_space (void);
static void _test_read_space_gcallback (void);
void test_read_word (void);
static void _test_read_word_gcallback (void);
void test_scan_word (void);
static void _test_scan_word_gcallback (void);
void test_check_char (void);
static void _test_check_char_gcallback (void);
void test_check_chars (void);
static void _test_check_chars_gcallback (void);
void test_check_chars_str (void);
static void _test_check_chars_str_gcallback (void);
void test_scan_char (void);


static void _test_read_space_gcallback (void) {
	test_read_space ();
}


static void _test_read_word_gcallback (void) {
	test_read_word ();
}


static void _test_scan_word_gcallback (void) {
	test_scan_word ();
}


static void _test_check_char_gcallback (void) {
	test_check_char ();
}


static void _test_check_chars_gcallback (void) {
	test_check_chars ();
}


static void _test_check_chars_str_gcallback (void) {
	test_check_chars_str ();
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	g_test_init (&args_length1, &args, NULL);
	g_test_add_func ("/crank/base/string/read/space", _test_read_space_gcallback);
	g_test_add_func ("/crank/base/string/read/word", _test_read_word_gcallback);
	g_test_add_func ("/crank/base/string/scan/word", _test_scan_word_gcallback);
	g_test_add_func ("/crank/base/string/check/char", _test_check_char_gcallback);
	g_test_add_func ("/crank/base/string/check/chars", _test_check_chars_gcallback);
	g_test_add_func ("/crank/base/string/check/chars_str", _test_check_chars_str_gcallback);
	g_test_run ();
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}


void test_read_space (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	guint space = 0U;
	guint _tmp1_ = 0U;
	gboolean _tmp2_ = FALSE;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
	guint _tmp5_ = 0U;
	gboolean _tmp6_ = FALSE;
	guint _tmp7_ = 0U;
	guint _tmp8_ = 0U;
	guint _tmp9_ = 0U;
	gboolean _tmp10_ = FALSE;
	guint _tmp11_ = 0U;
	guint _tmp12_ = 0U;
	guint _tmp13_ = 0U;
	gboolean _tmp14_ = FALSE;
	guint _tmp15_ = 0U;
	guint _tmp16_ = 0U;
	_tmp0_ = g_strdup ("  A string!");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp2_ = crank_str_read_space (subject, &pos, &_tmp1_);
	space = _tmp1_;
	_vala_assert (_tmp2_, "Crank.str_read_space (subject, ref pos, out space)");
	_tmp3_ = pos;
	_vala_assert (_tmp3_ == ((guint) 2), "pos == 2");
	_tmp4_ = space;
	_vala_assert (_tmp4_ == ((guint) 2), "space == 2");
	_tmp6_ = crank_str_read_space (subject, &pos, &_tmp5_);
	space = _tmp5_;
	_vala_assert (!_tmp6_, "! Crank.str_read_space (subject, ref pos, out space)");
	_tmp7_ = pos;
	_vala_assert (_tmp7_ == ((guint) 2), "pos == 2");
	_tmp8_ = space;
	_vala_assert (_tmp8_ == ((guint) 0), "space == 0");
	pos = (guint) 3;
	_tmp10_ = crank_str_read_space (subject, &pos, &_tmp9_);
	space = _tmp9_;
	_vala_assert (_tmp10_, "Crank.str_read_space (subject, ref pos, out space)");
	_tmp11_ = pos;
	_vala_assert (_tmp11_ == ((guint) 4), "pos == 4");
	_tmp12_ = space;
	_vala_assert (_tmp12_ == ((guint) 1), "space == 1");
	pos = (guint) 7;
	_tmp14_ = crank_str_read_space (subject, &pos, &_tmp13_);
	space = _tmp13_;
	_vala_assert (!_tmp14_, "! Crank.str_read_space (subject, ref pos, out space)");
	_tmp15_ = pos;
	_vala_assert (_tmp15_ == ((guint) 7), "pos == 7");
	_tmp16_ = space;
	_vala_assert (_tmp16_ == ((guint) 0), "space == 0");
	_g_free0 (subject);
}


void test_read_word (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gchar* word = NULL;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	guint _tmp3_ = 0U;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gchar* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	guint _tmp9_ = 0U;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	guint _tmp13_ = 0U;
	const gchar* _tmp14_ = NULL;
	_tmp0_ = g_strdup ("A quick brown fox jumps over the lazy dog");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp2_ = crank_str_read_word (subject, &pos, &_tmp1_);
	_g_free0 (word);
	word = _tmp1_;
	_vala_assert (_tmp2_, "Crank.str_read_word (subject, ref pos, out word)");
	_tmp3_ = pos;
	_vala_assert (_tmp3_ == ((guint) 1), "pos == 1");
	_tmp4_ = word;
	_vala_assert (g_strcmp0 (_tmp4_, "A") == 0, "word == \"A\"");
	_tmp6_ = crank_str_read_word (subject, &pos, &_tmp5_);
	_g_free0 (word);
	word = _tmp5_;
	_vala_assert (!_tmp6_, "! Crank.str_read_word (subject, ref pos, out word)");
	pos = (guint) 10;
	_tmp8_ = crank_str_read_word (subject, &pos, &_tmp7_);
	_g_free0 (word);
	word = _tmp7_;
	_vala_assert (_tmp8_, "Crank.str_read_word (subject, ref pos, out word)");
	_tmp9_ = pos;
	_vala_assert (_tmp9_ == ((guint) 13), "pos == 13");
	_tmp10_ = word;
	_vala_assert (g_strcmp0 (_tmp10_, "own") == 0, "word == \"own\"");
	pos = (guint) 20;
	_tmp12_ = crank_str_read_word (subject, &pos, &_tmp11_);
	_g_free0 (word);
	word = _tmp11_;
	_vala_assert (_tmp12_, "Crank.str_read_word (subject, ref pos, out word)");
	_tmp13_ = pos;
	_vala_assert (_tmp13_ == ((guint) 23), "pos == 23");
	_tmp14_ = word;
	_vala_assert (g_strcmp0 (_tmp14_, "mps") == 0, "word == \"mps\"");
	_g_free0 (word);
	_g_free0 (subject);
}


void test_scan_char (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gchar sym = '\0';
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gchar* _tmp3_ = NULL;
	gchar _tmp4_ = '\0';
	gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gchar* _tmp7_ = NULL;
	gchar _tmp8_ = '\0';
	gchar* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gchar* _tmp11_ = NULL;
	gchar _tmp12_ = '\0';
	gchar* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	gchar* _tmp15_ = NULL;
	_tmp0_ = g_strdup ("( : )");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp2_ = crank_str_scan_char (subject, &pos, &_tmp1_);
	_tmp3_ = _tmp1_;
	sym = *_tmp3_;
	_vala_assert (_tmp2_, "Crank.str_scan_char (subject, ref pos, out sym)");
	_g_free0 (_tmp3_);
	_tmp4_ = sym;
	_vala_assert (_tmp4_ == '(', "sym == '('");
	_tmp6_ = crank_str_scan_char (subject, &pos, &_tmp5_);
	_tmp7_ = _tmp5_;
	sym = *_tmp7_;
	_vala_assert (_tmp6_, "Crank.str_scan_char (subject, ref pos, out sym)");
	_g_free0 (_tmp7_);
	_tmp8_ = sym;
	_vala_assert (_tmp8_ == ':', "sym == ':'");
	_tmp10_ = crank_str_scan_char (subject, &pos, &_tmp9_);
	_tmp11_ = _tmp9_;
	sym = *_tmp11_;
	_vala_assert (_tmp10_, "Crank.str_scan_char (subject, ref pos, out sym)");
	_g_free0 (_tmp11_);
	_tmp12_ = sym;
	_vala_assert (_tmp12_ == ')', "sym == ')'");
	_tmp14_ = crank_str_scan_char (subject, &pos, &_tmp13_);
	_tmp15_ = _tmp13_;
	sym = *_tmp15_;
	_vala_assert (!_tmp14_, "! Crank.str_scan_char (subject, ref pos, out sym)");
	_g_free0 (_tmp15_);
	_g_free0 (subject);
}


void test_scan_word (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gchar* word = NULL;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	const gchar* _tmp9_ = NULL;
	_tmp0_ = g_strdup ("Cookie cake strawberry");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp2_ = crank_str_scan_word (subject, &pos, &_tmp1_);
	_g_free0 (word);
	word = _tmp1_;
	_vala_assert (_tmp2_, "Crank.str_scan_word (subject, ref pos, out word)");
	_tmp3_ = word;
	_vala_assert (g_strcmp0 (_tmp3_, "Cookie") == 0, "word == \"Cookie\"");
	_tmp5_ = crank_str_scan_word (subject, &pos, &_tmp4_);
	_g_free0 (word);
	word = _tmp4_;
	_vala_assert (_tmp5_, "Crank.str_scan_word (subject, ref pos, out word)");
	_tmp6_ = word;
	_vala_assert (g_strcmp0 (_tmp6_, "cake") == 0, "word == \"cake\"");
	_tmp8_ = crank_str_scan_word (subject, &pos, &_tmp7_);
	_g_free0 (word);
	word = _tmp7_;
	_vala_assert (_tmp8_, "Crank.str_scan_word (subject, ref pos, out word)");
	_tmp9_ = word;
	_vala_assert (g_strcmp0 (_tmp9_, "strawberry") == 0, "word == \"strawberry\"");
	_g_free0 (word);
	_g_free0 (subject);
}


void test_check_char (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	_tmp0_ = g_strdup ("( : )");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp1_ = crank_str_check_char (subject, &pos, ':');
	_vala_assert (!_tmp1_, "! Crank.str_check_char (subject, ref pos, ':')");
	_tmp2_ = crank_str_check_char (subject, &pos, '(');
	_vala_assert (_tmp2_, "Crank.str_check_char (subject, ref pos, '(')");
	_tmp3_ = crank_str_check_char (subject, &pos, ')');
	_vala_assert (!_tmp3_, "! Crank.str_check_char (subject, ref pos, ')')");
	_tmp4_ = crank_str_check_char (subject, &pos, ':');
	_vala_assert (_tmp4_, "Crank.str_check_char (subject, ref pos, ':')");
	_tmp5_ = crank_str_check_char (subject, &pos, ')');
	_vala_assert (_tmp5_, "Crank.str_check_char (subject, ref pos, ')')");
	_g_free0 (subject);
}


void test_check_chars (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gchar chars[3] = {0};
	gchar _tmp1_[3] = {0};
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	_tmp0_ = g_strdup ("( : ) ,");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp1_[0] = '(';
	_tmp1_[1] = ':';
	_tmp1_[2] = ')';
	memcpy (chars, _tmp1_, 3 * sizeof (gchar));
	_tmp2_ = crank_str_check_chars (subject, &pos, chars, (guint) 3);
	_vala_assert (0 == _tmp2_, "0 == Crank.str_check_chars (subject, ref pos, chars)");
	_tmp3_ = crank_str_check_chars (subject, &pos, chars, (guint) 3);
	_vala_assert (1 == _tmp3_, "1 == Crank.str_check_chars (subject, ref pos, chars)");
	_tmp4_ = crank_str_check_chars (subject, &pos, chars, (guint) 3);
	_vala_assert (2 == _tmp4_, "2 == Crank.str_check_chars (subject, ref pos, chars)");
	_tmp5_ = crank_str_check_chars (subject, &pos, chars, (guint) 3);
	_vala_assert ((-1) == _tmp5_, "-1 == Crank.str_check_chars (subject, ref pos, chars)");
	_g_free0 (subject);
}


void test_check_chars_str (void) {
	gchar* subject = NULL;
	gchar* _tmp0_ = NULL;
	guint pos = 0U;
	gchar* chars = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	_tmp0_ = g_strdup ("( : ) ,");
	subject = _tmp0_;
	pos = (guint) 0;
	_tmp1_ = g_strdup ("(:)");
	chars = _tmp1_;
	_tmp2_ = crank_str_check_chars_str (subject, &pos, chars);
	_vala_assert (0 == _tmp2_, "0 == Crank.str_check_chars_str (subject, ref pos, chars)");
	_tmp3_ = crank_str_check_chars_str (subject, &pos, chars);
	_vala_assert (1 == _tmp3_, "1 == Crank.str_check_chars_str (subject, ref pos, chars)");
	_tmp4_ = crank_str_check_chars_str (subject, &pos, chars);
	_vala_assert (2 == _tmp4_, "2 == Crank.str_check_chars_str (subject, ref pos, chars)");
	_tmp5_ = crank_str_check_chars_str (subject, &pos, chars);
	_vala_assert ((-1) == _tmp5_, "-1 == Crank.str_check_chars_str (subject, ref pos, chars)");
	_g_free0 (chars);
	_g_free0 (subject);
}



